In [1]:
import json_processing
import data_quality_checks
import pandas as pd
from tqdm import tqdm
# Define the keys to extract and their paths
keys = {
    'formThreeAList': ['projectExtra', 'getform-three-byid', 'data', 'formThreeAList'],
    'getProjectLocations': ['projectDetails', 'getProjectLocations'],
    'getproject-details': ['projectDetails', 'getproject-details', 'data'],
    'englist': ['projectDetails', 'getproject-details', 'data', 'englist'],
    'dev': ['projectDetails', 'getproject-details', 'data', 'dev'],
    'acrchlist': ['projectDetails', 'getproject-details', 'data', 'acrchlist'],
    'contr': ['projectDetails', 'getproject-details', 'data', 'contr'],
}

# TODO: Replace this with the list of your JSON files
# json_files = ["file1.json", "file2.json", "file3.json"]
# excel_writer = pd.ExcelWriter('Output/Guj-Rera Database 2022-December.xlsx', engine='xlsxwriter')
dfs = json_processing.process_json_files('Saved Jsons', keys)

        # Append the data to the initial DataFrames
        # for key, df in dfs.items():
        #     initial_dfs[key] = pd.concat([initial_dfs[key], df], ignore_index=True)

# TODO: Handle the output (e.g., save the DataFrames to CSV files or load them into a database)

Processing files: 100%|██████████| 9895/9895 [53:56<00:00,  3.06it/s]

In [6]:
# dfs = json_processing.process_json_file('Saved Jsons\80_242398.json',keys)
dfs.keys()

dict_keys(['formThreeAList', 'getProjectLocations', 'getproject-details', 'englist', 'dev', 'acrchlist', 'contr'])

In [5]:
dfs['getproject-details']

,englist,dev,calist,agentlist,acrchlist,contr,projectDetail.id,projectDetail.prjRegId,projectDetail.projectName,projectDetail.projectType,...,projectDetail.comDrinkWaterReq,projectDetail.totalDrinkWaterReq,projectDetail.resDrinkWaterProps,projectDetail.comDrinkWaterProps,projectDetail.totalDrinkWaterProps,projectDetail.totalwaterPropsPercen,projectDetail.waterSplyFromSource,projectDetail.waterSplyFromOther,projectDetail.startDateStr,projectDetail.completionDateStr
0,"[{'engineerId': 7051, 'projectRegId': 10001, '...","[{'devId': 50064, 'prjRegId': 10001, 'prjAppRe...",[],[],"[{'architectId': 7293, 'projectRegId': 10001, ...",[],8994,10001,THE RIDGE,Commercial,...,None,None,None,None,None,None,None,None,13-12-2019,30-06-2026
1,"[{'engineerId': 7086, 'projectRegId': 10002, '...","[{'devId': 50101, 'prjRegId': 10002, 'prjAppRe...",[],[],"[{'architectId': 7332, 'projectRegId': 10002, ...","[{'contractorId': 4300, 'contractortName': 'DW...",9040,10002,SHIV PRABHU ARC,Commercial,...,None,None,None,None,None,None,None,None,15-12-2019,31-03-2022
2,"[{'engineerId': 7044, 'projectRegId': 10003, '...","[{'devId': 50059, 'prjRegId': 10003, 'prjAppRe...",[],[],"[{'architectId': 7287, 'projectRegId': 10003, ...","[{'contractorId': 4286, 'contractortName': 'Sa...",8987,10003,AATREY IVAAN - 2,Residential/Group Housing,...,None,None,None,None,None,None,None,None,19-02-2020,30-06-2025
3,"[{'engineerId': 7271, 'projectRegId': 10004, '...","[{'devId': 50303, 'prjRegId': 10004, 'prjAppRe...",[],[],"[{'architectId': 7529, 'projectRegId': 10004, ...",[],9264,10004,SHASHWAT ELEGANCE,Mixed Development,...,None,None,None,None,None,None,None,None,01-08-2019,31-12-2022
4,"[{'engineerId': 7046, 'projectRegId': 10005, '...","[{'devId': 50061, 'prjRegId': 10005, 'prjAppRe...",[],[],"[{'architectId': 7288, 'projectRegId': 10005, ...",[],8989,10005,VICTORIAN OASIS,Residential/Group Housing,...,None,None,None,None,None,None,None,None,07-11-2019,30-06-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9890,"[{'engineerId': 7039, 'projectRegId': 9996, 'p...","[{'devId': 50056, 'prjRegId': 9996, 'prjAppReg...",[],[],"[{'architectId': 7282, 'projectRegId': 9996, '...","[{'contractorId': 4287, 'contractortName': 'S ...",8982,9996,OPERA HEIGHTS,Residential/Group Housing,...,None,None,None,None,None,None,None,None,27-11-2019,30-06-2024
9891,"[{'engineerId': 7037, 'projectRegId': 9997, 'p...","[{'devId': 50054, 'prjRegId': 9997, 'prjAppReg...",[],[],"[{'architectId': 7280, 'projectRegId': 9997, '...","[{'contractorId': 4281, 'contractortName': 'Pa...",8980,9997,Trisha Rudraksh,Mixed Development,...,None,None,None,None,None,None,None,None,03-11-2017,31-01-2025
9892,"[{'engineerId': 7533, 'projectRegId': 9998, 'p...","[{'devId': 50588, 'prjRegId': 9998, 'prjAppReg...",[],[],"[{'architectId': 7812, 'projectRegId': 9998, '...",[],9576,9998,VIBRANT CITY PHASE - 1,Commercial,...,None,None,None,None,None,None,None,None,01-06-2020,31-12-2025
9893,"[{'engineerId': 7042, 'projectRegId': 9999, 'p...","[{'devId': 50057, 'prjRegId': 9999, 'prjAppReg...",[],[],"[{'architectId': 7285, 'projectRegId': 9999, '...","[{'contractorId': 4284, 'contractortName': 'RA...",8985,9999,TULSI HEIGHTS,Residential/Group Housing,...,None,None,None,None,None,None,None,None,10-02-2020,30-06-2023
9894,[],"[{'devId': 42978, 'prjRegId': 999, 'prjAppRegI...",[],[],[],[],766,999,Colonnade II,Commercial,...,None,None,None,None,None,None,None,None,15-10-2016,31-12-2019

In [8]:
import pandas as pd
from tqdm import tqdm
# Create a Pandas Excel writer using the 'xlsxwriter' engine
excel_writer = pd.ExcelWriter('Output/Guj-Rera Database 2022-December.xlsx', engine='xlsxwriter')

# Iterate through the dictionary and write each DataFrame to a separate sheet
for sheet_name, df in tqdm(dfs.items()):
    # df.to_excel(excel_writer, sheet_name=sheet_name, index=False)
    df.to_csv(f"Output/{sheet_name}.csv")

# Save and close the Excel writer
# excel_writer.save()

100%|██████████| 7/7 [00:15<00:00,  2.17s/it]

In [6]:
dfs['englist']

,engineerId,projectRegId,projectAppRegId,engemailId,name,mobileNo,aadharNo,structuEnggPanNo,noOfKeyProjectsCompleted,licenceNO,addressLine,status,joinOn,separatedOn,profExperience
0,13,38,38,setuinf@gmail.com,Setu Infrastructure,None,None,None,800,SD046210620,"308 Abhishilp Complex, Above HDFC,",CONFIRMED,2017-09-27T12:44:43.000+0530,None,800
1,21,72,72,zarnaasso@gmail.com,ZARNA ASSOCIATES,None,None,None,4500,SH64/16-19,"14/ RATNAM APARTMENTS, OPP. NEPTUNE TOWER, NR....",CONFIRMED,2017-07-12T14:30:21.000+0530,None,4500

In [7]:
dfs['dev']

,devId,prjRegId,prjAppRegId,internalDev,waterLevel,waterLevelFlag,dateOfSoilReport,soilReportId,soilReportUid,waterSplyFlag,...,sewSwimCapHeight,seawageDisDistance,externalDev.extDevId,externalDev.developmentId,externalDev.roadSysetmDevBy,externalDev.waterSupplyBy,externalDev.sewegeAndDrainageSystemDevBy,externalDev.electricityAndTrasfomerSupply,externalDev.solidWasteSupplyBy,externalDev.extOtherDevSet
0,42449,38,38,"[{'internalDevId': 15, 'prjRegId': None, 'proj...",None,None,None,None,None,None,...,None,None,17,42449,Self Development,Local Authority,Local Authority,Local Authority,Self Development,[]
1,42454,72,72,[],None,None,None,None,None,None,...,None,None,37,42454,Self Development,Self Development,Self Development,Self Development,Local Authority,"[{'extOtherDevId': 15, 'externalDevelopmentId'..."

In [8]:
dfs['acrchlist']

,architectId,projectRegId,projectAppRegId,emailId,mobileNo,name,aadhaar,address,noOfKeyProjectCompleted,localAuthorityLicenceNo,panNo,profExperience,status,separatedOn,joinOn
0,2402,38,38,99studiodata@gmail.com,None,99Studio,None,"11th Floor, Landmark,Above SBI,",300,CA201569261,None,300,CONFIRMED,None,2017-09-27T12:44:43.000+0530
1,12,38,38,kamlesh@hcp.co.in,None,HCP Design Planning and Management Pvt Ltd,None,Paritosh,10000,200842516,None,10000,CONFIRMED,None,2017-09-27T12:44:43.000+0530
2,20,72,72,designstudio81@gmail.com,None,RUCHIR SHETH,None,"401, RADHESHYAM APPARTMENTS, OPP. VERAI MATA M...",500,CA/2011/53220,None,500,CONFIRMED,None,2017-07-12T14:30:21.000+0530

In [9]:
dfs['contr']

,contractorId,contractortName,prjRegId,prjAppRegId,emailId,mobileNo,address,aAdharNo,contractorPanNo,noofkeyprojectscompleted,noOfYearestablishment,profExperience
0,11,N R Insfrastructure Pvt Ltd,38,38,natwarlal_sharda@yahoo.co.in,None,shop no B-107 signature ii,None,None,60,None,None
1,17,VINS ASSOCIATES,72,72,vinsassociates2849.ps@gmail.com,None,"A-2 KHODAL NAGAR, NR. MANAV DHARAM ASHRAM,",None,None,20,None,None

In [5]:
dfs['getproject-details']

,englist,dev,calist,agentlist,acrchlist,contr,projectDetail.id,projectDetail.prjRegId,projectDetail.projectName,projectDetail.projectType,...,projectDetail.comDrinkWaterReq,projectDetail.totalDrinkWaterReq,projectDetail.resDrinkWaterProps,projectDetail.comDrinkWaterProps,projectDetail.totalDrinkWaterProps,projectDetail.totalwaterPropsPercen,projectDetail.waterSplyFromSource,projectDetail.waterSplyFromOther,projectDetail.startDateStr,projectDetail.completionDateStr
0,"[{'engineerId': 13, 'projectRegId': 38, 'proje...","[{'devId': 42449, 'prjRegId': 38, 'prjAppRegId...",[],[],"[{'architectId': 2402, 'projectRegId': 38, 'pr...","[{'contractorId': 11, 'contractortName': 'N R ...",17,38,Saujanya Apartments,Mixed Development,...,None,None,None,None,None,None,None,None,01-07-2017,30-12-2021
1,"[{'engineerId': 21, 'projectRegId': 72, 'proje...","[{'devId': 42454, 'prjRegId': 72, 'prjAppRegId...",[],[],"[{'architectId': 20, 'projectRegId': 72, 'proj...","[{'contractorId': 17, 'contractortName': 'VINS...",37,72,SARVA SQUARE,Mixed Development,...,None,None,None,None,None,None,None,None,08-04-2015,10-10-2027

In [4]:
dfs['getProjectLocations']

,locId,projectName,promotorName,projectCost,projectType,processType,promotorType,projectStatus,address,subDistrictCode,subDistrictName,districtCode,districtName,waterLevel,projectId,status,coordinates
0,3797,Saujanya Apartments,Saumya Construction Pvt Ltd,1785598580,Mixed Development,REG,Company,New Project Launch,"Nr. Anupam Cinema, Next to Ashima Mills,Shri K...",None,Ahmedabad City,AHME,Ahmedabad,None,38,SUCCESS,"[{'locId': 29319, 'lat': '23.00797855433928', ..."
1,9206,SARVA SQUARE,SARVA SWAMI DEVELOPERS,107125000,Mixed Development,REG,Partnership Firm,Ongoing,"NR. HARNI WATER TANK, MOTHNATH MAHADEV MANDIR ...",None,Vadodara,VADO,Vadodara,None,72,SUCCESS,"[{'locId': 64781, 'lat': '22.345731568861897',..."

In [3]:
dfs['formThreeAList']

,id,formThreePk,blockId,blockName,usage,flatNo,carpetArea,areaofExBalcony,status,unitConsideration,...,balanceAmount,encumbranceStatus,dateOfAgrrement,alloteeName,typeofKYC,kycId,redeveloped,mobileNumber,createdOn,kycid
0,29256899,285620,2443,Block A,Residential,A- 108,56.75,0.00,BOOKED,2802800,...,261550,Released,2017-12-09T00:00:00.000+0530,MANISH PANKAJRAI PARMAR,PAN,AOEPP0305F,NO,9998434205,None,AOEPP0305F
1,29256900,285620,2443,Block A,Residential,A- 109,56.75,0.00,BOOKED,2802800,...,0,Released,2018-02-13T00:00:00.000+0530,ATANU ASHUTOSH GHOSH,PAN,ADFPG3532M,NO,9724093445,None,ADFPG3532M
2,29256901,285620,2443,Block A,Residential,A- 110,56.75,0.00,BOOKED,2802800,...,133750,Released,2018-02-17T00:00:00.000+0530,CHANDRIKABEN BIPINBHAI VAISHNAV,PAN,CEFPS1286F,NO,9825052800,None,CEFPS1286F
3,29256902,285620,2443,Block A,Residential,A- 111,56.75,0.00,BOOKED,2802800,...,653136,Released,2017-12-18T00:00:00.000+0530,AMARKUMAR MADANLAL KOSHTI,PAN,DPKPK8996H,NO,7405868832,None,DPKPK8996H
4,29256903,285620,2443,Block A,Residential,A- 112,56.75,0.00,BOOKED,2802800,...,0,Released,2018-01-06T00:00:00.000+0530,GOKUL RAJRATAN MITTAL,PAN,BBMPM8371C,NO,9998702345,None,BBMPM8371C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,30543976,304134,None,C,Residential,C-401,54.66,4.47,BOOKED,1015072,...,0,No Encumbrance,None,EAST BROOK ESTATE,PAN,AABPU1344A,NO,9913000555,2022-08-05T12:00:10.351+0530,AABPU1344A
999,30543977,304134,None,C,Residential,C-402,54.66,4.47,BOOKED,1130000,...,0,No Encumbrance,None,EAST BROOK ESTATE,PAN,AABPU1344A,NO,9913000555,2022-08-05T12:00:10.351+0530,AABPU1344A
1000,30543978,304134,None,C,Residential,C-403,54.66,4.47,BOOKED,1745500,...,435500,No Encumbrance,None,EAST BROOK ESTATE,PAN,AABPU1344A,NO,9913000555,2022-08-05T12:00:10.352+0530,AABPU1344A
1001,30543979,304134,None,C,Residential,C-404,54.66,4.47,BOOKED,1792431,...,0,No Encumbrance,None,EAST BROOK ESTATE,PAN,AABPU1344A,NO,9913000555,2022-08-05T12:00:10.352+0530,AABPU1344A
1002,30543980,304134,None,C,Residential,C-501,54.66,4.47,BOOKED,1527165,...,0,No Encumbrance,None,EAST BROOK ESTATE,PAN,AABPU1344A,NO,9913000555,2022-08-05T12:00:10.352+0530,AABPU1344A

In [2]:
# Perform data quality checks
missing_values = data_quality_checks.check_missing_values(dfs)
print(missing_values)
duplicates = data_quality_checks.check_duplicates(dfs)
print(f'Number of duplicate rows: {duplicates}')
constant_columns = data_quality_checks.check_constant_columns(dfs)
print(f'Constant columns: {constant_columns}')
summary_stats = data_quality_checks.summary_statistics(dfs)
print(summary_stats)

NameError: name 'dfs' is not defined

In [4]:
import requests
import pandas as pd
import time
from tqdm import tqdm
import json
import os
# getAllProjectsURL = 'http://3.111.75.239/dashboard/get-district-wise-projectlist/0/0/all/all/all'
# data = requests.get(getAllProjectsURL).json()
# data

In [ ]:
pd.DataFrame.from_dict(data['data']).to_csv('responses/Project List 2022 - 9895.csv',index=False)

In [7]:
os.chdir('/content/drive/Shareddrives/Pruthvi Shared/Rera Scrapping Old Version')
projectList = pd.read_csv('responses/Project List 2022 - 9895.csv')
projectList.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9895 entries, 0 to 9894
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pr_mobile_no            9895 non-null   int64
 1   projOrgFDate            9895 non-null   object
 2   wfoid                   9895 non-null   object
 3   prmtr_adhaar_no         0 non-null      float64
 4   project_status          9895 non-null   object
 5   approvedOn              9895 non-null   object
 6   hardcopysubmissionDate  9895 non-null   object
 7   projectCost             9829 non-null   float64
 8   projectType             9895 non-null   object
 9   prmtr_com_reg_no        321 non-null    object
 10  districtName            9895 non-null   object
 11  project_address         9841 non-null   object
 12  total_est_cost_of_proj  9829 non-null   float64
 13  payment_status          9895 non-null   object
 14  regNo                   9895 non-null   object
 15  startDate               9895 non-null   object
 16  endDate                 9895 non-null   object
 17  districtType            9895 non-null   object
 18  projectName             9895 non-null   object
 19  promoterAddress         340 non-null    object
 20  regFee                  9895 non-null   float64
 21  project_cost            9817 non-null   float64
 22  projectRegId            9895 non-null   int64
 23  prmtr_pan_no            364 non-null    object
 24  pmtr_email_id           9895 non-null   object
 25  extDate                 1558 non-null   object
 26  project_ack_no          9895 non-null   object
 27  promoterName            9895 non-null   object
 28  disposed_date           0 non-null      float64
 29  payment_token           9895 non-null   object
dtypes: float64(6), int64(2), object(22)
memory usage: 2.3+ MB

In [ ]:
def getAllDetailsbyProject(projID):
    alldatabyprojectid = f"http://3.111.75.239/project_reg/public/alldatabyprojectid/{projID}"
    getproject_details = f"http://3.111.75.239/project_reg/public/getproject-details/{projID}"
    getproject_banks = f"http://3.111.75.239/project_reg/public/project-app/getproject-banks/{projID}"
    getProjectProgressReports_ByPrjRegId = f"http://3.111.75.239/project_reg/public/getProjectProgressReports-ByPrjRegId/{projID}"
    getproject_doc = f"http://3.111.75.239/project_reg/public/getproject-doc/{projID}"
    getProjectLocations = f"http://3.111.75.239/maplocation/public/getProjectLocations/{projID}"
    projectDetails = [alldatabyprojectid,getproject_details,getproject_banks,getProjectProgressReports_ByPrjRegId,getproject_doc,getProjectLocations]
    dataDictProject = {}
    for dataPoint in tqdm(projectDetails):
        jsonData = requests.get(dataPoint).json()
        # dataDf = pd.DataFrame.from_dict(jsonData['data'])
        dataDictProject[dataPoint.split('/')[-2]] = jsonData
        time.sleep(2)

    time.sleep(5)
    form3ID = dataDictProject['alldatabyprojectid']['data']['formThreeId']
    form2ID = dataDictProject['alldatabyprojectid']['data']['formTwoId']
    form1ID = dataDictProject['alldatabyprojectid']['data']['formOneId']

    getform_three_byid = f"http://3.111.75.239/formthree/public/getform-three-byid/{form3ID}"

    getform_two_by_id = f"http://3.111.75.239/formtwo/public/getform-two-by-id/{form2ID}"

    getfrom_one_byformone_id = f"http://3.111.75.239/formone/public/getfrom-one-byformone-id/{form1ID}"

    extraDetails = [getform_three_byid,getform_two_by_id,getfrom_one_byformone_id]
    dataDictExtra = {}
    for dataPoint in tqdm(extraDetails):
        jsonData = requests.get(dataPoint).json()
        dataDictExtra[dataPoint.split('/')[-2]] = jsonData
        time.sleep(2)
    # print(dataDict)
    jsonDict = {'projectDetails':dataDictProject,
            'projectExtra':dataDictExtra}

    with open(f"Saved Jsons/{projID}_{form3ID}.json", "w") as outfile:
        json.dump(jsonDict, outfile)
    return jsonDict

In [ ]:
projectList[['projectName','projectRegId']]

              projectName  projectRegId
0           Aashray Arise            12
1     Saujanya Apartments            38
2        Santorini Square            58
3     PURE BY SANGATH IPL            62
4            SARVA SQUARE            72
...                   ...           ...
9890             Random 1         14388
9891    Payments in PR OE         14391
9892           Test 01/03         14395
9893       test extension         14402
9894          New TP Auth         14457

[9895 rows x 2 columns]

In [ ]:
sampleDict = getAllDetailsbyProject(12)

100%|██████████| 6/6 [00:14<00:00,  2.46s/it]

In [ ]:
sampleDict['projectExtra']